### ISSUE TITLE
Error upon launch: Invalid configured_addr

### ISSUE THREAD

**Issue by mountainsandcode** [alex20465/bluedesk#3]
Hi,

Looking for a Python based tool to control my IKEA desk and saw your project. Installation through PIP works fine, but I get an error on first launch

> Traceback (most recent call last):
  File "/usr/local/bin/bluedesk", line 86, in <module>
    raise Exception("Invalid configured address:" + configured_addr)
Exception: Invalid configured address:

I haven't been able to get it to work supplying a MAC-Address through --addr either, which I see has been defined in the file. Any ideas what could solve this problem? Would be greatly appreciated.

**Comment by alex20465** [comment]
Did you executed the `connect` command ? 

after the successful `connect` command a configuration file should be created with the following content:

```
[default]
addr = e4:d1:a7:7e:xx:xx
```

**Comment by mountainsandcode** [comment]
Yes, indeed I started with the connect command but I get the error message on first launch. Where would the configuration file normally be located?

**Comment by noxhirsch** [comment]
I have exactly the same problem. Both on an Intel NUC with Ubuntu and on a Raspberry Pi Zero W with Raspbian. 
Additionally I tried to add the address in a file bluedesk.conf in `/usr/local/lib/python3.7/dist-packages/bluedesk`, but I don't know if this is the right path - it also didn't work.

**Comment by alex20465** [comment]
I will try to reproduce

**Comment by alex20465** [comment]
Checkout the 1.9 version, Personally I have some issues with my devices and bluepy but raspberry works perfectly.

Otherwise, the bluetooth manager keeps the connection alive as paired, this is why other command will not work after the connection, also bluepy is totally unreliable with some distributions. Sry I just connect and use the services with the command line tool.

**Comment by noxhirsch** [comment]
The scanning does work now (thank you for that fast fix!), but on both of our desks Bluedesk says, that the desk (freshly bought IKEA IDASEN) is not compatible :(
Out of curiousity I removed the check of the MAC address and got this feedback:
```
Device: f8:e1:XX:XX:XX:84 connected successfully.
Exception ignored in: <function Peripheral.__del__ at 0xb60ebd68>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 631, in __del__
    self.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 453, in disconnect
    self._writeCmd("disc\n")
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 304, in _writeCmd
    self._helper.stdin.write(cmd)
ValueError: I/O operation on closed file.
```

Do you have any idea what the problem could be? And if you need more information, what can I do?

By the way: The MAC addresses are completely different on my desks. They don't have any similar number blocks.

**Comment by alex20465** [comment]
OK so the mac-address has no constant suffix, i will just remove it. The error you got is a disconnection error and can be ignored, did you try to perform up/down actions ?

**Comment by noxhirsch** [comment]
I tried with no success. When I type `bluedesk up`, I get this multiple times:
`Connection failed: Failed to connect to peripheral f8:e1:XX:XX:XX:84, addr type: random`

By the way: When I connect the desk and my console says connected and throwing the error, the desks bluetooth LED is still blinking.

**Comment by alex20465** [comment]
I get the exact the same behaviour on ubuntu system but it works fine on raspberry-pi.

**Comment by noxhirsch** [comment]
Maybe the Raspberry Pi Zero W is the problem? What Version do you use?
I could try on my Raspberry Pi 4 on another MicroSD card.

**Comment by noxhirsch** [comment]
Additionally: What OS are you using? I used the newest image of Raspbian Buster Lite.

**Comment by alex20465** [comment]
I use raspberrypi 3,  its not the models issue. Its a known issue of bluepy, it can't disconnect connected devices. You could try to disconnect the bluetooth device manually, then you could run a single action until it goes to the same issue.

**Comment by noxhirsch** [comment]
Oh yeah! I just got it running on my Raspberry Pi 4 🎉 (will counter check later if it is working on my Zero now, too - but I really didn't do anything else than before)
I have another problem, but I'll open a new issue for that.

**Comment by noxhirsch** [comment]
Now I've counter checked it: The connection problem was because of the Raspberry Pi Zero.
