### ISSUE TITLE
Device is not supported

### ISSUE THREAD

**Issue by hsolberg** [alex20465/bluedesk#6]
Hi! I would love to use this for automation with HomeAssistant. How can I help getting my desk supported? Any commands you need me to run to check the capabilities of the desk to look for differences between the desk you're using and the one I have?

I'm using this to enable bluetooth on my desk since it's not bluetooth-enabled natively: https://www.linak.com/products/accessories/bluetooth-adapter-desk/

I'm not sure what the Linak model-number is for the motor. Here's the log when I tried to connect.

```Scanning ...
[?] Choice device: BLE2LIN 6671


Traceback (most recent call last):
  File "/usr/local/bin/bluedesk", line 97, in <module>
    action()
  File "/usr/local/bin/bluedesk", line 37, in action_connect
    manager.connect(answer.get("device_addr"))
  File "/usr/local/lib/python3.8/site-packages/bluedesk/manager.py", line 46, in connect
    raise Exception("Device is not supported")
Exception: Device is not supported
```

*EDIT*
I just noticed your other project, is that meant to be the replacement for this or a complimentary program? https://github.com/alex20465/deskbluez

**Comment by alex20465** [comment]
I will no longer maintain bluedesk, checkout the require: https://github.com/alex20465/deskbluez
